### ISSUE TITLE
Cant parse saves with custom user markers

### ISSUE THREAD

**Issue by karlas** [omni-resources/civ6-save-parser#3]
Hi!

While playing PYDT, i created a user marker in my turn. After trying to submit savegame, error appeared.

Replayed turn without placing the marker, and all went fine.

I attach you this savegame with the marker (renamed to txt)

[PEDRO 10 3640 a. C..Civ6Save.txt](https://github.com/omni-resources/civ6-save-parser/files/691505/PEDRO.10.3640.a.C.Civ6Save.txt)

Thx for your work!

**Comment by mrosack** [comment]
Thanks!  I've fixed the parser, and I'll get it integrated into PYDT today, hopefully on your next turn it'll work. :)

Fixed in 36996b5f8b36e886b8f7a42c11e0a247be8b86d1

**Comment by karlas** [comment]
That was fast! Thx!
