### ISSUE TITLE
Error opening savegames on Mac

### ISSUE THREAD

**Issue by karlas** [omni-resources/civ6-save-parser#4]
Not really sure if it's the parser or any other agent of PYDT...

When opening a save game with mac, game load exits after few seconds of showing the "loading" screens (where the civ leader and its description appears).

Reproduced with two different games. On windows, it works fine

**Comment by mrosack** [comment]
This is an issue with the Mac build - the Australian Summer update hasn't been released for OS X yet, so save files saved on Windows with the update will be unreadable by the OS X build.

**Comment by karlas** [comment]
Ok top!
