### ISSUE TITLE
is grammar file up-to-date?

### ISSUE THREAD

**Issue by ntcong** [omni-resources/civ6-save-parser#8]
I'm trying to figuring out more data in civ6's save file. I opened the file with a hex editor but the grammar file seems to be not correct, it got civ name, game turn, etc all wrong.

The parser works fine, so maybe it's just not up-to-date?

**Comment by mrosack** [comment]
The grammar file was added by a friend of mine when we first started working on this, but it's definitely out of date and i'm not sure it was ever accurate.  I'll go ahead and delete it, thanks!
